apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-app
spec:
  containers:
  - name: app-except-db
    image: dminus251/except_db:latest
    ports:
    - containerPort: 5000

